# encoding: utf-8
Refinery::Pages.configure do |config|

  # Define global page parts
  # Remember that parts :title, :body, :side_body
  # are required for proper behaviour as core refinerycms but also other extensions
  # config.parts = [:title, :perex, :body, :side_body]

  # Configure global page parts where are active by default
  # config.default_parts = [:title, :body, :side_body]

  # Configure whether to enable marketable_urls
  # config.marketable_urls = true

  # Configure how many pages per page should be displayed in the list of pages in the admin area
  # config.per_admin_page = 20

  # Configure how many pages per page should be displayed in link dialog
  # config.per_dialog_page = 20

  # Set this to true if page slugs generated by friendly_id should be scoped by parent.
  # If false, page slugs are global, and are, in effect, custom routes that may contain slashes.
  # By default, these routes will be flattened to the root, using the slugged page title,
  # and will no longer be nested as children.
  # config.scope_slug_by_parent = true

  # Set this to true to fully expand the page hierarchy in the admin
  # config.auto_expand_admin_tree = true

  # config.layout_template_whitelist = ["application"]

  # config.use_layout_templates = false

  # config.page_title = {:chain_page_title=>false, :ancestors=>{:separator=>" | ", :class=>"ancestors", :tag=>"span"}, :page_title=>{:class=>nil, :tag=>nil, :wrap_if_not_chained=>false}}

end
